"""
Language parsers for the Code Knowledge Graph (CKG) system.

This module contains language-specific parsers that extract code constructs
from Abstract Syntax Trees (AST) generated by tree-sitter.
"""

from .c_parser import recursive_visit_c
from .cpp_parser import recursive_visit_cpp
from .csharp_parser import recursive_visit_csharp
from .dart_parser import recursive_visit_dart
from .elixir_parser import recursive_visit_elixir
from .gleam_parser import recursive_visit_gleam
from .go_parser import recursive_visit_go
from .java_parser import recursive_visit_java
from .javascript_parser import recursive_visit_javascript
from .kotlin_parser import recursive_visit_kotlin
from .php_parser import recursive_visit_php
from .python_parser import recursive_visit_python
from .ruby_parser import recursive_visit_ruby
from .rust_parser import recursive_visit_rust
from .scala_parser import recursive_visit_scala
from .solidity_parser import recursive_visit_solidity
from .svelte_parser import recursive_visit_svelte
from .swift_parser import recursive_visit_swift
from .typescript_parser import recursive_visit_typescript
from .vue_parser import recursive_visit_vue
from .zig_parser import recursive_visit_zig

__all__ = [
    "recursive_visit_c",
    "recursive_visit_cpp",
    "recursive_visit_csharp",
    "recursive_visit_dart",
    "recursive_visit_elixir",
    "recursive_visit_gleam",
    "recursive_visit_go",
    "recursive_visit_java",
    "recursive_visit_javascript",
    "recursive_visit_kotlin",
    "recursive_visit_php",
    "recursive_visit_python",
    "recursive_visit_ruby",
    "recursive_visit_rust",
    "recursive_visit_scala",
    "recursive_visit_solidity",
    "recursive_visit_svelte",
    "recursive_visit_swift",
    "recursive_visit_typescript",
    "recursive_visit_vue",
    "recursive_visit_zig",
]
